// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoaG9VSnf4JMWkF9jP7uFq1PCoddMuOg4',
    appId: '1:832701424902:web:8f95fc242a0f7f97c1ea87',
    messagingSenderId: '832701424902',
    projectId: 'todoma',
    authDomain: 'todoma-d4000.firebaseapp.com',
    storageBucket: 'todoma.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKI8aiuB52vhBVRZJSNG1uo-yfzp1LKiI',
    appId: '1:832701424902:android:5234ca5ce4451f4cc1ea87',
    messagingSenderId: '832701424902',
    projectId: 'todoma',
    storageBucket: 'todoma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzrh-aoNaxPSntZ_A13ENIHMUXKkwNo9k',
    appId: '1:832701424902:ios:91eb54bfc850ac4fc1ea87',
    messagingSenderId: '832701424902',
    projectId: 'todoma',
    storageBucket: 'todoma.appspot.com',
    iosClientId: '832701424902-9nhb968ghvp7es3lb98ljq3tdpedsmc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataStatement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzrh-aoNaxPSntZ_A13ENIHMUXKkwNo9k',
    appId: '1:832701424902:ios:fb5244200bf0edd0c1ea87',
    messagingSenderId: '832701424902',
    projectId: 'todoma',
    storageBucket: 'todoma.appspot.com',
    iosClientId: '832701424902-42arf0lrad0vrufktu30gej06ekon31e.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataStatement.RunnerTests',
  );
}
